# Подключение к БД (PostgreSQL 17)
db.url=jdbc:postgresql://localhost:5432/otp_service
db.user=otp_user
db.password=1725

# HTTP сервер
server.port=8080

# JWT
jwt.secret=NOnCK9sNk3AZOFU1uVMRpjIvJXxZe0l0Kv71w4QQvsW8HvcVmzHZX4P0uM5vw9gi
jwt.ttl.minutes=60

# Шедулер истечения OTP
# Раз в сколько секунд сканировать просроченные коды
scheduler.expire.period.seconds=30
